services:
   mysql:
      image: mariadb:lts
      restart: unless-stopped
      command:
         - '--character-set-server=utf8mb4'
         - '--collation-server=utf8mb4_unicode_ci'
         - '--skip-name-resolve'
      cap_add:
         - SYS_NICE
      environment:
         MYSQL_ALLOW_EMPTY_PASSWORD: 'false' # Disallow empty password
         MYSQL_INITDB_SKIP_TZINFO: '1' # Skip loading DB time zone tables (improves performance)
         ### Database initialization ###
         MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
         MYSQL_DATABASE: ${DB_DATABASE}
         MYSQL_USER: ${DB_USER}
         MYSQL_PASSWORD: ${DB_PASSWORD}
      volumes:
         - mysql_volume:/var/lib/mysql
      networks:
         app:

   wp:
      image: wordpress:php8.4-apache
      restart: unless-stopped
      depends_on:
         - mysql
      environment:
         WORDPRESS_DB_HOST: mysql:3306
         WORDPRESS_DB_NAME: ${DB_DATABASE}
         WORDPRESS_DB_USER: ${DB_USER}
         WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
         LETSENCRYPT_HOST: ${WP_DOMAIN}
         VIRTUAL_HOST: ${WP_DOMAIN}
         VIRTUAL_PORT: 80
      volumes:
         - wp_volume:/var/www/html
         - ./wordpress/wp.php.ini:/usr/local/etc/php/conf.d/wp.php.ini
      networks:
         app:
         main-nginx-proxy:
      # healthcheck:
      #    test: ["CMD", "curl", "-f", "http://localhost/"]
      #    interval: 30s
      #    timeout: 10s
      #    retries: 5

   pma:
      image: phpmyadmin:latest
      restart: unless-stopped
      depends_on:
         - mysql
      environment:
         PMA_HOST: mysql
         PMA_PORT: 3306
         PMA_USER: ${DB_USER}
         PMA_PASSWORD: ${DB_PASSWORD}
         LETSENCRYPT_HOST: ${PMA_DOMAIN}
         VIRTUAL_HOST: ${PMA_DOMAIN}
         VIRTUAL_PORT: 80
      networks:
         app:
         main-nginx-proxy:
      # healthcheck:
      #    test: ["CMD", "curl", "-f", "http://localhost/"]
      #    interval: 30s
      #    timeout: 10s
      #    retries: 5

   files:
      image: filebrowser/filebrowser:latest
      restart: unless-stopped
      depends_on:
         - wp
      environment:
         LETSENCRYPT_HOST: ${FILES_DOMAIN}
         VIRTUAL_HOST: ${FILES_DOMAIN}
         VIRTUAL_PORT: 80
      volumes:
         - wp_volume:/srv
         - fb_volume:/fb_data
         - ./filebrowser/filebrowser.json:/.filebrowser.json
      networks:
         app:
         main-nginx-proxy:

volumes:
   mysql_volume:
      driver: local
   wp_volume:
      driver: local
   fb_volume:
      driver: local

networks:
   app:
      external: false
   main-nginx-proxy:
      external: true
